-- Backfill sku_fornecedor dos itens importados
update public.estoque_itens set sku_fornecedor = '54991' where ativo = true and upper(trim(nome)) = upper(trim('ABRAC SELIM ALUM 34.9MM C/BLOC PTO - WG SPORTS - WGSEL0023'));
update public.estoque_itens set sku_fornecedor = '53129' where ativo = true and upper(trim(nome)) = upper(trim('ADAPT DE VALVULA PRESTA P/AMERICANA PCT C/10 - WG SPORTS - WGVAL0001'));
update public.estoque_itens set sku_fornecedor = '111153' where ativo = true and upper(trim(nome)) = upper(trim('ARO 16 16 FUROS NATURAL - VZAN - 8310/70592/PAC000224'));
update public.estoque_itens set sku_fornecedor = '111158' where ativo = true and upper(trim(nome)) = upper(trim('ARO 20 36 FUROS NATURAL - VZAN - 8338 /70568 /PAC000229'));
update public.estoque_itens set sku_fornecedor = '107598' where ativo = true and upper(trim(nome)) = upper(trim('ARO 26 1.9 36 FUROS P06 NATURAL - VZAN - 8369 /70535 /PAC000237'));
update public.estoque_itens set sku_fornecedor = '152612' where ativo = true and upper(trim(nome)) = upper(trim('ARO 26 36 FUROS ESCAPE CNC PRETO - VZAN - 301280 /PAC000145'));
update public.estoque_itens set sku_fornecedor = '150785' where ativo = true and upper(trim(nome)) = upper(trim('ARRUELA DE EIXO TRASEIRO 3/8 FRESADA ZINC - NEK - 3003 / 04091005'));
update public.estoque_itens set sku_fornecedor = '152770' where ativo = true and upper(trim(nome)) = upper(trim('BAGAGEIRO 26 FEM PRETO - SAMY - 000000000005759'));
update public.estoque_itens set sku_fornecedor = '154313' where ativo = true and upper(trim(nome)) = upper(trim('BAGAGEIRO ARTICULADO MTB BASE RETA PTO - SAMY - 35785 / 32467'));
update public.estoque_itens set sku_fornecedor = '151356' where ativo = true and upper(trim(nome)) = upper(trim('BAGAGEIRO FEM ROSA - SAMY - 2113'));
update public.estoque_itens set sku_fornecedor = '151357' where ativo = true and upper(trim(nome)) = upper(trim('BAGAGEIRO FEM VIOLETA - SAMY - 1633'));
update public.estoque_itens set sku_fornecedor = '153540' where ativo = true and upper(trim(nome)) = upper(trim('BICICLETA ARO 12 FEM CHARM RSA/VDE - NATHOR - 100010160050/108001000008'));
update public.estoque_itens set sku_fornecedor = '153544' where ativo = true and upper(trim(nome)) = upper(trim('BICICLETA ARO 12 FEM FLOWERS MOD NOVO RSA - NATHOR - 100010160038/10800100001'));
update public.estoque_itens set sku_fornecedor = '154230' where ativo = true and upper(trim(nome)) = upper(trim('BICICLETA ARO 12 MASC VELOZ MOD NOVO AZL/PTO PU - NATHOR - 100010160040'));
update public.estoque_itens set sku_fornecedor = '151436' where ativo = true and upper(trim(nome)) = upper(trim('BICICLETA ARO 16 TOP GIRLS 6 - NATHOR - 100130160026'));
update public.estoque_itens set sku_fornecedor = '153041' where ativo = true and upper(trim(nome)) = upper(trim('BICICLETA BALANCE BIKE FAST MOD 3 - NATHOR - 100900160015'));
update public.estoque_itens set sku_fornecedor = '60271' where ativo = true and upper(trim(nome)) = upper(trim('BLOCAGEM DE SELIM ALUM 6X60MM PTO - COMANDER - CMBLO0002'));
update public.estoque_itens set sku_fornecedor = '8098' where ativo = true and upper(trim(nome)) = upper(trim('BOMBA DE OFICINA 580X29MM ALUM C/CBO PLAST POLIDA - WG SPORTS - WGBOM0002'));
update public.estoque_itens set sku_fornecedor = '8102' where ativo = true and upper(trim(nome)) = upper(trim('BRACO ESQUERDO PDV 170MM CZA - WG SPORTS - WGPDV0004'));
update public.estoque_itens set sku_fornecedor = '154365' where ativo = true and upper(trim(nome)) = upper(trim('CADEIRINHA DIANT BABY BIKE KF400 GRAFITE/PTO - KALF - 04400521'));
update public.estoque_itens set sku_fornecedor = '154372' where ativo = true and upper(trim(nome)) = upper(trim('CADEIRINHA TRAS KID BIKE KF402 GRAFITE/PTO - KALF - 04402521'));
update public.estoque_itens set sku_fornecedor = '150587' where ativo = true and upper(trim(nome)) = upper(trim('CADEIRINHA TRAS PTO - PROMOPAIRE - CNA-29020-52'));
update public.estoque_itens set sku_fornecedor = '153774' where ativo = true and upper(trim(nome)) = upper(trim('CAIXA DE CUBO DIANT 25MM COMPAT SHUMFENG PCT 10 UNID - NEK - 04150121'));
update public.estoque_itens set sku_fornecedor = '153773' where ativo = true and upper(trim(nome)) = upper(trim('CAIXA DE CUBO TRAS 29MM C/BATENTE PCT 10 UNID - NEK - 04150223'));
update public.estoque_itens set sku_fornecedor = '54966' where ativo = true and upper(trim(nome)) = upper(trim('CAMARA PB-26 VALV AMERICANA 32MM - PIRELLI IMP - 2106700'));
update public.estoque_itens set sku_fornecedor = '60337' where ativo = true and upper(trim(nome)) = upper(trim('CAMBIO TRAS 18/21V S/GANCHEIRA PTO - COMANDER - CMCAM0007'));
update public.estoque_itens set sku_fornecedor = '60263' where ativo = true and upper(trim(nome)) = upper(trim('CANOTE SELIM C/CARRINHO 27.2X350MM PTO - COMANDER - CMCAN0001'));
update public.estoque_itens set sku_fornecedor = '58243' where ativo = true and upper(trim(nome)) = upper(trim('CANOTE SELIM C/CARRINHO 30.4X400MM PTO FOSCO - HIGH ONE - HOCAN0014'));
update public.estoque_itens set sku_fornecedor = '58485' where ativo = true and upper(trim(nome)) = upper(trim('CANOTE SELIM S/CARRINHO 27.2X350MM PTO - WG SPORTS - WGCAN0016'));
update public.estoque_itens set sku_fornecedor = '152786' where ativo = true and upper(trim(nome)) = upper(trim('CARAMANHOLA HIGH ONE EQUIPE 500ML BCO - SQUEEZE TOTAL - KEQ6012035004'));
update public.estoque_itens set sku_fornecedor = '152174' where ativo = true and upper(trim(nome)) = upper(trim('CARAMANHOLA SENSE 500ML BCO/AZL AQUA - SQUEEZE TOTAL - K6012185002'));
update public.estoque_itens set sku_fornecedor = '8116' where ativo = true and upper(trim(nome)) = upper(trim('CASTANHA DE SELIM PTO - WG SPORTS - WGSEL0002'));
update public.estoque_itens set sku_fornecedor = '10159' where ativo = true and upper(trim(nome)) = upper(trim('CESTA ARAME COMP 31X23X23 C/CINTO PTO - WG SPORTS - WGCES0003'));
update public.estoque_itens set sku_fornecedor = '8117' where ativo = true and upper(trim(nome)) = upper(trim('CESTA ARAME COMP 35X25X26 C/CINTO PTO - WG SPORTS - WGCES0001'));
update public.estoque_itens set sku_fornecedor = '55553' where ativo = true and upper(trim(nome)) = upper(trim('CHAVE DE RAIO - WG SPORTS - WGFER0005'));
update public.estoque_itens set sku_fornecedor = '10626' where ativo = true and upper(trim(nome)) = upper(trim('CHAVE DE RAIO 8 BOCAS CROMADA - SUPER B - TB-5510'));
update public.estoque_itens set sku_fornecedor = '10588' where ativo = true and upper(trim(nome)) = upper(trim('CHAVE EXTRATOR DE MOV CENTRAL HOLLOWTECH 2 C/CABO - SUPER B - TB-BB10'));
update public.estoque_itens set sku_fornecedor = '10589' where ativo = true and upper(trim(nome)) = upper(trim('CHAVE EXTRATOR DE MOV CENTRAL PONTA QUADRADA C/CABO - SUPER B - TB-BB30'));
update public.estoque_itens set sku_fornecedor = '10635' where ativo = true and upper(trim(nome)) = upper(trim('CHAVE EXTRATOR DE PDV PONTA QUADRADA S/CABO - SUPER B - TB- 6618'));
update public.estoque_itens set sku_fornecedor = '11296' where ativo = true and upper(trim(nome)) = upper(trim('CICLO COMPUTADOR 11 FUNCOES AS-520 PTO - ASSIZE - AS-520'));
update public.estoque_itens set sku_fornecedor = '57376' where ativo = true and upper(trim(nome)) = upper(trim('CICLO COMPUTADOR 15 FUNCOES C/FIO C/LUZ PTO - HIGH ONE - HOCIC0002'));
update public.estoque_itens set sku_fornecedor = '57377' where ativo = true and upper(trim(nome)) = upper(trim('CICLO COMPUTADOR 15 FUNCOES WIRELESS C/LUZ PTO - HIGH ONE - HOCIC0003'));
update public.estoque_itens set sku_fornecedor = '152376' where ativo = true and upper(trim(nome)) = upper(trim('COLA P/ REMENDO CVB-01 (CAIXA COM 24 UNIDADES) - VULCAFLEX - 1345'));
update public.estoque_itens set sku_fornecedor = '8124' where ativo = true and upper(trim(nome)) = upper(trim('COLAR DE ESFERAS CUBO TRAS 1/4X7 ACO - WG SPORTS - WGCOL0002'));
update public.estoque_itens set sku_fornecedor = '8125' where ativo = true and upper(trim(nome)) = upper(trim('COLAR DE ESFERAS MOV CENTR 45 1/4X10 ACO - WG SPORTS - WGCOL0004'));
update public.estoque_itens set sku_fornecedor = '57229' where ativo = true and upper(trim(nome)) = upper(trim('CORRENTE FINA C10 MTB INDEX 1/2X11/128X116 - TEC - C10'));
update public.estoque_itens set sku_fornecedor = '7766' where ativo = true and upper(trim(nome)) = upper(trim('CORRENTE FINA C30 1/2X3/32X116 ELOS INDEX - TEC - C30'));
update public.estoque_itens set sku_fornecedor = '10679' where ativo = true and upper(trim(nome)) = upper(trim('CORRENTE FINA SEMI-INDEX HV500 6/7V 116 LINKS CZA/MARROM - KMC - HV500'));
update public.estoque_itens set sku_fornecedor = '7769' where ativo = true and upper(trim(nome)) = upper(trim('CORRENTE GROSSA C410 1/2X1/8X114 ELOS - TEC - C410'));
update public.estoque_itens set sku_fornecedor = '8145' where ativo = true and upper(trim(nome)) = upper(trim('CUBO ACO DIANT 36F CROM - WG SPORTS - WGCUB0002'));
update public.estoque_itens set sku_fornecedor = '8148' where ativo = true and upper(trim(nome)) = upper(trim('CUBO ACO TRAS C/ESPACADOR 36F CROM - WG SPORTS - WGCUB0007'));
update public.estoque_itens set sku_fornecedor = '56706' where ativo = true and upper(trim(nome)) = upper(trim('CUBO ALUM DIANT DISCO 36F B27 PTO - HIGH ONE - HOCUB0009'));
update public.estoque_itens set sku_fornecedor = '53213' where ativo = true and upper(trim(nome)) = upper(trim('CUBO ALUM DIANT DISCO 36F C/BLOC PTO - WG SPORTS - WGCUB0011'));
update public.estoque_itens set sku_fornecedor = '53214' where ativo = true and upper(trim(nome)) = upper(trim('CUBO ALUM TRAS DISCO 36F C/BLOC PTO - WG SPORTS - WGCUB0012'));
update public.estoque_itens set sku_fornecedor = '60866' where ativo = true and upper(trim(nome)) = upper(trim('CUBO CONTRA PEDAL DE ENCAIXE COMPLETO - WG SPORTS - WGCUB0017'));
update public.estoque_itens set sku_fornecedor = '59843' where ativo = true and upper(trim(nome)) = upper(trim('DESCANSO CENTRAL CAVALETE ALUM TAM 26 PTO - WG SPORTS - WGDES0005'));
update public.estoque_itens set sku_fornecedor = '107073' where ativo = true and upper(trim(nome)) = upper(trim('DESCANSO CENTRAL S/REGULAGEM PTO / POL - GLOMETAL - 376/2146'));
update public.estoque_itens set sku_fornecedor = '60234' where ativo = true and upper(trim(nome)) = upper(trim('DESCANSO LATERAL 24 C/MOLA ACO ZINCADO - COMANDER - CMDES0002'));
update public.estoque_itens set sku_fornecedor = '11279' where ativo = true and upper(trim(nome)) = upper(trim('DESCANSO LATERAL 26 C/MOLA ACO REFORC PTO - WG SPORTS - WGDSC0004'));
update public.estoque_itens set sku_fornecedor = '60299' where ativo = true and upper(trim(nome)) = upper(trim('DISCO ROTOR 160MM CROM - COMANDER - CMFRE0010'));
update public.estoque_itens set sku_fornecedor = '57382' where ativo = true and upper(trim(nome)) = upper(trim('EIXO DIANT 3/8X108MM ACO FURADO AX01 PTO - WG SPORTS - WGEIX0009'));
update public.estoque_itens set sku_fornecedor = '55610' where ativo = true and upper(trim(nome)) = upper(trim('EIXO DIANT 3/8X140MM COMPLETO - WG SPORTS - WGEIX0006'));
update public.estoque_itens set sku_fornecedor = '60767' where ativo = true and upper(trim(nome)) = upper(trim('EIXO TRAS 3/8 X200MM C/ESPACADOR NIQUELADO - COMANDER - CMEIX0003'));
update public.estoque_itens set sku_fornecedor = '58025' where ativo = true and upper(trim(nome)) = upper(trim('EMENDA DE CORRENTE POWER LINK 11V CARTELA C/2 - KMC - CL555R'));
update public.estoque_itens set sku_fornecedor = '107226' where ativo = true and upper(trim(nome)) = upper(trim('ENGRENAGEM 32D ACO ZINC - PROJEMA - XRC-7 013'));
update public.estoque_itens set sku_fornecedor = '57651' where ativo = true and upper(trim(nome)) = upper(trim('ESPACADOR A SET ALUM OVER 5MM PTO - WG SPORTS - WGESP0002'));
update public.estoque_itens set sku_fornecedor = '58174' where ativo = true and upper(trim(nome)) = upper(trim('EXTRATOR DE PINO DE CORRENTE GROSSA E 6 A 10 VEL-ECONOMICO - SUPER B - TB-3306'));
update public.estoque_itens set sku_fornecedor = '9424' where ativo = true and upper(trim(nome)) = upper(trim('EXTRATOR RODA LIVRE K7 MODELO HG - SUPER B - TB-1010'));
update public.estoque_itens set sku_fornecedor = '150859' where ativo = true and upper(trim(nome)) = upper(trim('FITA ANTI FURO MTB 35 MM ARO 29 - TECTIRE - 102029'));
update public.estoque_itens set sku_fornecedor = '60793' where ativo = true and upper(trim(nome)) = upper(trim('FITA DE GUIDAO 213X3CM RELEVO PU/EVA PTO - HIGH ONE - HOFIT0008'));
update public.estoque_itens set sku_fornecedor = '60474' where ativo = true and upper(trim(nome)) = upper(trim('FREIO VARAO DIANT/TRAS CROMADO - COMANDER - CMFRE0013'));
update public.estoque_itens set sku_fornecedor = '152518' where ativo = true and upper(trim(nome)) = upper(trim('GANCHEIRA ELITE 30/CORRATEC/SENSE PTA - GANTECH - 10006/ GE006'));
update public.estoque_itens set sku_fornecedor = '154166' where ativo = true and upper(trim(nome)) = upper(trim('GANCHEIRA GTS M1 - GANTECH - GE036'));
update public.estoque_itens set sku_fornecedor = '152019' where ativo = true and upper(trim(nome)) = upper(trim('GARFO 20 MTB CANTILEVER PRETO BRILHANTE - SAMY - 1718'));
update public.estoque_itens set sku_fornecedor = '59919' where ativo = true and upper(trim(nome)) = upper(trim('GARFO SUSP 26/21.1 V-BRAKE C/ROSCA PRETO - MODE - MDGRF0063'));
update public.estoque_itens set sku_fornecedor = '58241' where ativo = true and upper(trim(nome)) = upper(trim('GARFO SUSP 29 ACO 25.4MM DISCO PTO (GORDO) - HIGH ONE - HOGRF0012'));
update public.estoque_itens set sku_fornecedor = '153026' where ativo = true and upper(trim(nome)) = upper(trim('GRAXA AMARELA PREMIUM BK 2000 500G - TECTIRE - 751004'));
update public.estoque_itens set sku_fornecedor = '150116' where ativo = true and upper(trim(nome)) = upper(trim('GUIDAO CB400 SEM EXPANDIR PRETO - CARRERA - 1304SP'));
update public.estoque_itens set sku_fornecedor = '154290' where ativo = true and upper(trim(nome)) = upper(trim('GUIDAO CROSS ALTO PRETO - CARRERA - 1215SP'));
update public.estoque_itens set sku_fornecedor = '8169' where ativo = true and upper(trim(nome)) = upper(trim('GUIDAO DOWH HILL MEDIO ACO PTO - WG SPORTS - WGGDA0001'));
update public.estoque_itens set sku_fornecedor = '150121' where ativo = true and upper(trim(nome)) = upper(trim('GUIDAO POTI EXPANDIDO CROMADO COM RELEVO - CARRERA - 1202EC'));
update public.estoque_itens set sku_fornecedor = '150124' where ativo = true and upper(trim(nome)) = upper(trim('GUIDAO TITAN/CG SEM EXPANDIR CROMADO - CARRERA - 1211SC'));
update public.estoque_itens set sku_fornecedor = '50519' where ativo = true and upper(trim(nome)) = upper(trim('KIT CAMBIO DIANT/TRAS C/GAN E ALAV 18V - WG SPORTS - WGCAM0006'));
update public.estoque_itens set sku_fornecedor = '58632' where ativo = true and upper(trim(nome)) = upper(trim('LUVA CYCLE DEDO FECHADO TAM G PTO/BRANCO - WG SPORTS - WGLUV0009'));
update public.estoque_itens set sku_fornecedor = '59555' where ativo = true and upper(trim(nome)) = upper(trim('LUVA CYCLE DEDO FECHADO TAM M PTO/BRANCO - WG SPORTS - WGLUV0011'));
update public.estoque_itens set sku_fornecedor = '58628' where ativo = true and upper(trim(nome)) = upper(trim('LUVA CYCLE DEDO VAZADO TAM G CINZA/AMARELO - WG SPORTS - WGLUV0005'));
update public.estoque_itens set sku_fornecedor = '107711' where ativo = true and upper(trim(nome)) = upper(trim('MANOPLA ADVENTURE PTO - WESTER - WM1090'));
update public.estoque_itens set sku_fornecedor = '60490' where ativo = true and upper(trim(nome)) = upper(trim('MANOPLA ECO - COMANDER - CMMAN0004'));
update public.estoque_itens set sku_fornecedor = '60889' where ativo = true and upper(trim(nome)) = upper(trim('MANOPLA FREERIDE JOKER 160MM LARANJA/PTO - HIGH ONE - HOMAN0040'));
update public.estoque_itens set sku_fornecedor = '107710' where ativo = true and upper(trim(nome)) = upper(trim('MANOPLA MIRIM PTO - WESTER - WM111E'));
update public.estoque_itens set sku_fornecedor = '60286' where ativo = true and upper(trim(nome)) = upper(trim('MOV CENTRAL INTEGRADO TIPO SHIMANO NYLON PTO - COMANDER - CMMOC0002'));
update public.estoque_itens set sku_fornecedor = '60610' where ativo = true and upper(trim(nome)) = upper(trim('MOV CENTRAL SALVA QUADRO 68 X 122.5 MM - WG SPORTS - WGMOC0001'));
update public.estoque_itens set sku_fornecedor = '50783' where ativo = true and upper(trim(nome)) = upper(trim('MOV CENTRAL SALVA QUADRO 68X122,5MM - NECO - NCMOC0016'));
update public.estoque_itens set sku_fornecedor = '7391' where ativo = true and upper(trim(nome)) = upper(trim('MOV CENTRAL SELADO C/ROL 68X122.5MM - NECO - NCMOC0008'));
update public.estoque_itens set sku_fornecedor = '7394' where ativo = true and upper(trim(nome)) = upper(trim('MOV CENTRAL SELADO C/ROL 68X127.5MM - NECO - NCMOC0011'));
update public.estoque_itens set sku_fornecedor = '60281' where ativo = true and upper(trim(nome)) = upper(trim('MOV DIR OVER C/ROSCA ACO COMPLETO PTO - COMANDER - CMMOD0004'));
update public.estoque_itens set sku_fornecedor = '107134' where ativo = true and upper(trim(nome)) = upper(trim('PARAF P/PARALAMAS - LUGLI - PB1012'));
update public.estoque_itens set sku_fornecedor = '107135' where ativo = true and upper(trim(nome)) = upper(trim('PARAFUSO P/SELIM SEXTAVADO LONGO PCT C/ 50 - LUGLI - PB5134/PC 5134'));
update public.estoque_itens set sku_fornecedor = '150173' where ativo = true and upper(trim(nome)) = upper(trim('PARALAMA DIAN/TRAS TERRA FORTE PTO - SAMY - 3752'));
update public.estoque_itens set sku_fornecedor = '150170' where ativo = true and upper(trim(nome)) = upper(trim('PARALAMA DIANT/TRAS TERRA FORTE AZL - SAMY - 3748'));
update public.estoque_itens set sku_fornecedor = '150172' where ativo = true and upper(trim(nome)) = upper(trim('PARALAMA DIANT/TRAS TERRA FORTE VMO - SAMY - 3749'));
update public.estoque_itens set sku_fornecedor = '57487' where ativo = true and upper(trim(nome)) = upper(trim('PDV MONOBLOCO 15X140MM CROM - NECO - NCPDV0002'));
update public.estoque_itens set sku_fornecedor = '7158' where ativo = true and upper(trim(nome)) = upper(trim('PDV TRIPLA MTB 170MM 28/38(PTA)/48 PTO BRACO PRETO - HIGH ONE - HOPDV0006'));
update public.estoque_itens set sku_fornecedor = '60343' where ativo = true and upper(trim(nome)) = upper(trim('PDV TRIPLA P/MTB 170MM RED 24/34/42 PTO - COMANDER - CMPDV0001'));
update public.estoque_itens set sku_fornecedor = '107649' where ativo = true and upper(trim(nome)) = upper(trim('PEDAL 1/2 MIRIM NY C/REFL. PTO - ROYAL CICLO - 50110000'));
update public.estoque_itens set sku_fornecedor = '152564' where ativo = true and upper(trim(nome)) = upper(trim('PEDAL 1/2 TREKKING NYLON PTO - ROYAL CICLO - 53101000'));
update public.estoque_itens set sku_fornecedor = '57668' where ativo = true and upper(trim(nome)) = upper(trim('PEDAL 9/16 PLATAFORMA ALUM PTO - WG SPORTS - WGPED0001'));
update public.estoque_itens set sku_fornecedor = '152565' where ativo = true and upper(trim(nome)) = upper(trim('PEDAL 9/16 TREKKING NYLON PTO - ROYAL CICLO - 53101001'));
update public.estoque_itens set sku_fornecedor = '107415' where ativo = true and upper(trim(nome)) = upper(trim('PEDALEIRA ALUMINIO TROLHINHA AZUL - UNICICLI - 102080103'));
update public.estoque_itens set sku_fornecedor = '107416' where ativo = true and upper(trim(nome)) = upper(trim('PEDALEIRA ALUMINIO TROLHINHA POLIDO - UNICICLI - 102080110'));
update public.estoque_itens set sku_fornecedor = '107412' where ativo = true and upper(trim(nome)) = upper(trim('PEDALEIRA ALUMINIO TROLHINHA PRETO - UNICICLI - 102080111'));
update public.estoque_itens set sku_fornecedor = '107413' where ativo = true and upper(trim(nome)) = upper(trim('PEDALEIRA ALUMINIO TROLHINHA VERMELHO - UNICICLI - 102080115'));
update public.estoque_itens set sku_fornecedor = '54960' where ativo = true and upper(trim(nome)) = upper(trim('PNEU 16X1.75 TOP CROSS PTO - PIRELLI IMP - 2664500'));
update public.estoque_itens set sku_fornecedor = '58093' where ativo = true and upper(trim(nome)) = upper(trim('PNEU 26X1.1/2X2 H-5211 SKINWALL BANDA LEVE PTO - CHAOYANG - CYPNE0059'));
update public.estoque_itens set sku_fornecedor = '58016' where ativo = true and upper(trim(nome)) = upper(trim('PNEU 26X1.95 H-5201 SKINWALL - CHAOYANG - CYPNE0056'));
update public.estoque_itens set sku_fornecedor = '55301' where ativo = true and upper(trim(nome)) = upper(trim('PNEU 29X2.10 H-5129 VICTORY - CHAOYANG - CYPNE0015'));
update public.estoque_itens set sku_fornecedor = '56040' where ativo = true and upper(trim(nome)) = upper(trim('PNEU 29X2.20 SCORPION PRO - PIRELLI IMP - 2667100'));
update public.estoque_itens set sku_fornecedor = '8182' where ativo = true and upper(trim(nome)) = upper(trim('PORCA DO EIXO TRAS E DIANT - WG SPORTS - WGPOR0001'));
update public.estoque_itens set sku_fornecedor = '10994' where ativo = true and upper(trim(nome)) = upper(trim('RAIO 2.0X185MM NIPLE ACO PTO - WG SPORTS - WGRAI0035'));
update public.estoque_itens set sku_fornecedor = '10992' where ativo = true and upper(trim(nome)) = upper(trim('RAIO 2.0X262MM NIPLE ACO PTO - WG SPORTS - WGRAI0033'));
update public.estoque_itens set sku_fornecedor = '8188' where ativo = true and upper(trim(nome)) = upper(trim('RAIO 2.0X262MM NIPLE ACO ZINCADO - WG SPORTS - WGRAI0006'));
update public.estoque_itens set sku_fornecedor = '52254' where ativo = true and upper(trim(nome)) = upper(trim('RAIO 2.0X290MM NIPLE ACO FINO PTO - WG SPORTS - WGRAI0040'));
update public.estoque_itens set sku_fornecedor = '8199' where ativo = true and upper(trim(nome)) = upper(trim('RAIO 2.5X265MM NIPLE ACO ZINCADO - WG SPORTS - WGRAI0015'));
update public.estoque_itens set sku_fornecedor = '58467' where ativo = true and upper(trim(nome)) = upper(trim('REFIL CILINDRO CO2 SENTEC 16G - SENTEC - STBOM0006'));
update public.estoque_itens set sku_fornecedor = '152370' where ativo = true and upper(trim(nome)) = upper(trim('REMENDO BLACK 30MM V-0 REDONDO (CAIXA COM 100 UNIDADES) - VULCAFLEX - 1300'));
update public.estoque_itens set sku_fornecedor = '9003' where ativo = true and upper(trim(nome)) = upper(trim('ROLAMENTO 6000 P/CUBO DIANTEIRO - WG SPORTS - WGROL0001'));
update public.estoque_itens set sku_fornecedor = '60305' where ativo = true and upper(trim(nome)) = upper(trim('SAPATA V-BRAKE PINO 70MM PTO - COMANDER - CMFRE0006'));
update public.estoque_itens set sku_fornecedor = '59960' where ativo = true and upper(trim(nome)) = upper(trim('SELIM 02 MOLAS PLUS PRETO - HIGH ONE - HOSEL0038'));
update public.estoque_itens set sku_fornecedor = '60363' where ativo = true and upper(trim(nome)) = upper(trim('SELIM 2 MOLAS PTO - COMANDER - CMSEL0011'));
update public.estoque_itens set sku_fornecedor = '154394' where ativo = true and upper(trim(nome)) = upper(trim('SELIM BARRA CIRCULAR SEM MOLAS COM CARRINHO - ROYAL CICLO - 102601000'));
update public.estoque_itens set sku_fornecedor = '60356' where ativo = true and upper(trim(nome)) = upper(trim('SELIM BMX MIRIM C/ CARRINHO PRETO - COMANDER - CMSEL0004'));
update public.estoque_itens set sku_fornecedor = '107634' where ativo = true and upper(trim(nome)) = upper(trim('SELIM MIRIM TOY PVC C/CANOTE PTO - ROYAL CICLO - 107071000'));
update public.estoque_itens set sku_fornecedor = '56697' where ativo = true and upper(trim(nome)) = upper(trim('SUPORTE ADAPT A SET ALUM 21.1X150MM PTO - WG SPORTS - WGSPA0001'));
update public.estoque_itens set sku_fornecedor = '107114' where ativo = true and upper(trim(nome)) = upper(trim('SUPORTE ADAPT FREIO CANTIL DIANT ZINCADO - JKS - 900775122/900775120'));
update public.estoque_itens set sku_fornecedor = '58096' where ativo = true and upper(trim(nome)) = upper(trim('SUPORTE CARAMANHOLA NYLON PTO - WG SPORTS - WGSPC0004'));
update public.estoque_itens set sku_fornecedor = '60423' where ativo = true and upper(trim(nome)) = upper(trim('SUPORTE GUIDAO MTB 31.8MMX80MM +-7º - COMANDER - CMSPG0003'));
update public.estoque_itens set sku_fornecedor = '60426' where ativo = true and upper(trim(nome)) = upper(trim('SUPORTE GUIDAO ALUM 31.8MMX60MM +-17º - HIGH ONE - HOSPG0051'));
update public.estoque_itens set sku_fornecedor = '60422' where ativo = true and upper(trim(nome)) = upper(trim('SUPORTE GUIDAO ALUM 31.8MMX60MM +-7º - COMANDER - CMSPG0002'));
update public.estoque_itens set sku_fornecedor = '60429' where ativo = true and upper(trim(nome)) = upper(trim('SUPORTE GUIDAO ALUM 31.8MMX80MM - COMANDER - CMSPG0005'));
update public.estoque_itens set sku_fornecedor = '60424' where ativo = true and upper(trim(nome)) = upper(trim('SUPORTE GUIDAO ALUM 31.8MMX90MM +-7º - COMANDER - CMSPG0004'));
update public.estoque_itens set sku_fornecedor = '58490' where ativo = true and upper(trim(nome)) = upper(trim('SUPORTE GUIDAO ALUM 31.8X0X40MM PTO FOSCO - HIGH ONE - HOSPG0043'));
update public.estoque_itens set sku_fornecedor = '107430' where ativo = true and upper(trim(nome)) = upper(trim('SUPORTE GUIDAO CROSS JR ALUM VERMELHO - UNICICLI - 103050115'));
update public.estoque_itens set sku_fornecedor = '107432' where ativo = true and upper(trim(nome)) = upper(trim('SUPORTE GUIDAO CROSS JR ALUMINIO AZUL - UNICICLI - 103050103'));
update public.estoque_itens set sku_fornecedor = '107429' where ativo = true and upper(trim(nome)) = upper(trim('SUPORTE GUIDAO CROSS JR ALUMINIO PRETO - UNICICLI - 103050111'));
update public.estoque_itens set sku_fornecedor = '8222' where ativo = true and upper(trim(nome)) = upper(trim('SUSPENSAO TRAS 165X7X650LB CROM - WG SPORTS - WGSTR0002'));
update public.estoque_itens set sku_fornecedor = '56879' where ativo = true and upper(trim(nome)) = upper(trim('TAMPA DE VALVULA TIPO BALA PEQUENA PRETO - WG SPORTS - WGVAL0013'));
update public.estoque_itens set sku_fornecedor = '154228' where ativo = true and upper(trim(nome)) = upper(trim('TERMINAL CABO DE FREIO (CENTO) - AVIOS - TC1003'));
update public.estoque_itens set sku_fornecedor = '107618' where ativo = true and upper(trim(nome)) = upper(trim('TRANSBIKE P/2 BIKES MODELO II - METAL LINI - 1002/1034'));
update public.estoque_itens set sku_fornecedor = '50917' where ativo = true and upper(trim(nome)) = upper(trim('TUBO GUIA P/FREIO V-BRAKE+BORRACHA ANTI PO - WG SPORTS - WGCBO0009'));
update public.estoque_itens set sku_fornecedor = '56682' where ativo = true and upper(trim(nome)) = upper(trim('VISTA LIGHT TRAS 5 FUNCOES C/RECARGA USB PTO - HIGH ONE - HOLUZ0024'));